## SPDX-FileCopyrightText: 2023 Open Networking Foundation <info@opennetworking.org>
##
## SPDX-License-Identifier: Apache-2.0
##
info:
  version: 1.0.0
  description: UDR initial local configuration

configuration:
  sbi: # Service Based Interface
    scheme: https
    registerIPv4: 127.0.0.4
    bindingIPv4: 0.0.0.0
    port: 8000
  mongodb:
    name: free5gc
    url: http://dummy
    authKeysDbName: authentication
    authUrl: http://dummy
  plmnSupportList:
    - plmnId:
        mcc: "208"
        mnc: "93"
      snssaiList:
        - sst: 1
          sd: "010203"

